// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbwxbhhoawmnamkpwjhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJid3hiaGhvYXdtbmFta3B3amhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTQ1MzEsImV4cCI6MjA2OTkzMDUzMX0.ZVBYwXd6FmM04hM8kJkeu2WMed4eQi502A7Y1dO1K5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});